server:
  port: 18082
spring:
  data:
    mongodb:
      uri: mongodb://192.168.100.100:27017/tanhua
dubbo:
  application:
    name: tanhua-recommend
  registry:
    address: zookeeper://192.168.100.100:2181
rocketmq:
  name-server: 192.168.100.100:9876