server:
  port: 18083

#配置mysql,redis
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tanhua-manager?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.100.100
    port: 6379
dubbo:
  application:
    name: tanhua-manage
  registry:
    address: zookeeper://192.168.100.100:2181
#配置短信平台信息
tanhua:
  secret: tanhua
  #替换成自己的 oss存储信息
  sms:
    signName: 袁小杰
    templateCode: SMS_99320050
    accessKey: LTAI6oNQblwg4mjc
    secret: pBJAfwYp0bo4EZWiBA5LfOK1qgMHln
  #替换成自己的 oss存储信息
  oss:
    accessKey: LTAI5tChsjKMkYNrNKegkerH
    secret: QM0SINvWofwDorIf7gnIdIbDhSghDg
    bucketName: williams-tanhua
    endpoint: oss-cn-beijing.aliyuncs.com
    url: https://williams-tanhua.oss-cn-beijing.aliyuncs.com
  aip:
    appId: 24117357
    apiKey: jzclZfQljgSqDfWp2XXLZHUU
    secretKey: vnjbAoMRxAL5Me5xxmnXOdAjZBiBAPKu
  huanxin:
    url: http://a1.easemob.com/
    orgName: 1109210512148046
    appName: tanhua
    clientId: YXA6-SEYRIT7TJ-6I9I8jxi4YA
    clientSecret: YXA6lGM-E-dkCKgtyHtOfy41GKB25ac
  huawei:
    username: tanhua
    password: tanhua123
    project: cn-north-1
    domain: odd466b7514015027768
    # 图片检测内容 politics：是否涉及政治人物的检测，terrorism：是否包含涉政暴恐元素的检测，porn：是否包含涉黄内容元素的检测，ad：是否包含广告的检测（公测特性），all：包含politics、terrorism和porn三种场景的检测
    cagegoriesImage: politics,terrorism,porn
    # 文字检测内容 politics：涉政，porn：涉黄，ad：广告，abuse：辱骂，contraband：违禁品，flood：灌水
    cagegoriesText: politics,porn,ad,abuse,contraband,flood
#mybaits-plus
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_    #数据库表前缀
      id-type: auto        #数据库表主键的策略
rocketmq:
  name-server: 192.168.100.100:9876