server:
  port: 18080
dubbo:
  application:
    name: tanhua-server
  registry:
    address: 

tanhua:
  secret: 
  sms:
    signName: 
    templateCode: 
    accessKey: 
    secret: 
  oss:
    accessKey: 
    secret: 
    bucketName: 
    endpoint: 
    url: 
  aip:
    appId: 
    apiKey: 
    secretKey: 
  huanxin:
    url: 
    orgName: 
    appName: 
    clientId: 
    clientSecret: 

spring:
  redis:
    host: 192.168.100.100
    port: 6379

# springmvc文件上传默认文件大小是1MB，所以需要在`tanhua-server`工程中的`application:yml`配置文件中，设置文件上传的大小限制。
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB

# ===================================================================
# 分布式文件系统FDFS配置  mac不能用docker的fastDFS
# ===================================================================
# fdfs:
#   so-timeout: 1500
#   connect-timeout: 600
#   #缩略图生成参数
#   thumb-image:
#     width: 150
#     height: 150
#   #TrackerList参数,支持多个
#   tracker-list: 192.168.85.40:22122
#   web-server-url: http://192.168.85.40:8888/
rocketmq:
  name-server: 192.168.100.100:9876
  producer:
    group: tanhua
